<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKxolwmm\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKxolwmm/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerKxolwmm.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerKxolwmm\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerKxolwmm\appProdProjectContainer([
    'container.build_hash' => 'Kxolwmm',
    'container.build_id' => '70e48e55',
    'container.build_time' => 1643149133,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKxolwmm');
